apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::629382421139:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AFBJY93GC8BI
      username: system:node:{{EC2PrivateDNSName}}
      groups:
         - system:bootstrappers
         - system:nodes
    - rolearn: arn:aws:iam::629382421139:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
